### ISSUE TITLE
ember-component-css incompatibility

### ISSUE THREAD

**Issue by buschtoens** [xomaczar/ember-cli-styles-reloader#8]
As brought up here: https://github.com/xomaczar/ember-cli-styles-reloader/issues/1#issuecomment-120557588

**Comment by buschtoens** [comment]
Working on a PR for you.

**Comment by buschtoens** [comment]
There's a problem. `ember-component-css` genereates a stylesheet like this:

``` css
.application--nav-bar-ecf9bbbf .wrapper {
  max-width: 400px;
  margin: 0 auto; }
```

Unfortunately, the class name suffix up there is absolutely random and changes with _every_ edit. Therefore it also needs to change in the document. This is clearly out of scope for this project, I'd say.

I'll open an issue over at `ember-component-css`.
